#!/usr/bin/env python3
"""Exact checks of the six-state reference loop; Python standard library only."""
from itertools import product
import json

STATES = tuple(product(range(3), (0, 1)))


def read(z):
    return int(z[0] == 2)


def select(z):
    return z[1]


def lift(z, a):
    s, r = z
    sn = (s + a) % 3
    return sn, r ^ int(sn == 1)


def update(z):
    return lift(z, select(z))


def inverse(z):
    sn, rn = z
    r = rn ^ int(sn == 1)
    return (sn - r) % 3, r


def run(z, count):
    path = [z]
    for _ in range(count):
        z = update(z)
        path.append(z)
    return path


def history(z, k):
    path = [z]
    for _ in range(k):
        path.insert(0, inverse(path[0]))
    return path


def window_classes(k, include_actions):
    groups = {}
    for z in STATES:
        path = history(z, k)
        sig = (tuple(map(read, path)),
               tuple(map(select, path[:-1])) if include_actions else ())
        groups.setdefault(sig, []).append(z)
    return list(groups.values())


def verify():
    report = {"arithmetic": "exact integers; no random samples"}
    for z in STATES:
        assert inverse(update(z)) == z
        assert update(inverse(z)) == z
        assert run(z, 4)[-1] == z
    report["state_table"] = [
        {"state": z, "output": read(z), "selected_action": select(z),
         "next_state": update(z)} for z in STATES]

    left, right = (0, 0), (1, 0)
    rows = []
    for t in range(9):
        assert left != right
        rows.append({"t": t, "left": left, "right": right,
                     "outputs": (read(left), read(right)),
                     "actions": (select(left), select(right)),
                     "difference": ((right[0] - left[0]) % 3, left[1] ^ right[1])})
        left, right = update(left), update(right)
    assert rows[0]["left"][1] == rows[0]["right"][1]  # shared reference initially
    assert rows[1]["left"][1] != rows[1]["right"][1]  # E, generated by F
    assert rows[3]["left"][0] == rows[3]["right"][0]  # pure reference difference
    assert rows[3]["actions"] == (0, 1)              # F, same object condition
    assert rows[4]["left"][0] != rows[4]["right"][0] # action changes motion
    assert rows[4]["left"][1] == rows[4]["right"][1]
    assert rows[5]["left"][1] != rows[5]["right"][1]  # G, generated again
    assert rows[4]["difference"] == rows[0]["difference"]
    report["E_H_pair"] = rows

    # All distinct pairs remain distinct: exact preservation of pair identity,
    # not a claim that each component difference is a conserved number.
    pair_count = 0
    for x, y in product(STATES, repeat=2):
        if x != y:
            assert update(x) != update(y)
            pair_count += 1
    report["distinct_pairs_preserved_in_one_step"] = pair_count

    # Validate r_t = r_0 XOR parity of post-update visits to marker 1.
    parity_count = 0
    for z in STATES:
        sn, rn = update(z)
        assert rn == z[1] ^ int(sn == 1)
        parity_count += 1
        accumulated = z[1]
        for state in run(z, 12)[1:]:
            accumulated ^= int(state[0] == 1)
            assert accumulated == state[1]
    report["history_identity"] = {"all_local_cases": parity_count,
                                  "cycles_per_initial_state_checked": 3,
                                  "arbitrary_length": "by induction on the local identity"}

    # The controlled plant projection is exactly the phase-1 Sol kernel.
    for z, a in product(STATES, (0, 1)):
        assert lift(z, a)[0] == (z[0] + a) % 3
    words = {"alpha": (0, 1, 0), "beta": (1, 1, 1), "gamma": (0, 1, 1)}
    controlled_paths = {}
    for name, word in words.items():
        z, path = (0, 0), [(0, 0)]
        for a in word:
            z = lift(z, a)
            path.append(z)
        controlled_paths[name] = path
    assert read(controlled_paths["alpha"][-1]) == read(controlled_paths["beta"][-1]) == 0
    assert read(controlled_paths["gamma"][-1]) == 1
    report["C0_controlled_projection"] = {"one_step_cases": 12,
                                          "paths": controlled_paths,
                                          "scope": "controlled family, not closed-loop path freedom"}

    # This event output sequence separates every full state with 4 samples.
    report["R1_windows"] = {}
    for with_actions in (False, True):
        key = "outputs_and_past_actions" if with_actions else "outputs_only"
        partitions = [window_classes(k, with_actions) for k in range(4)]
        minimum = next(k for k, part in enumerate(partitions) if len(part) == len(STATES))
        assert minimum == (2 if with_actions else 3)
        report["R1_windows"][key] = {
            "class_counts_for_k_0_to_3": list(map(len, partitions)),
            "minimum_k": minimum,
            "partition_one_shorter": partitions[minimum - 1]}

    # Ablations: either coupling removed breaks a different leg of the loop.
    def no_write(z):
        s, r = z
        return (s + r) % 3, r
    def no_feedback(z):
        s, r = z
        return s, r ^ int(s == 1)
    for s in range(3):
        for r in (0, 1):
            assert no_write((s, r))[1] == r
        assert no_feedback((s, 0))[0] == no_feedback((s, 1))[0] == s
    assert update((1, 0))[0] != update((1, 1))[0]
    report["ablations"] = {"remove_reference_write": "E fails",
                           "remove_reference_feedback": "F/G fail",
                           "drop_reference_from_state": "no well-defined object-only update"}

    # Optional INPUT-driven pausing, deliberately outside the autonomous model.
    # Identity pause allows arbitrary identical recent windows, but a release
    # separates the outputs. Algebraically this holds for every pause length.
    pause_pair = ((1, 0), (1, 1))
    assert read(pause_pair[0]) == read(pause_pair[1])
    assert read(update(pause_pair[0])) != read(update(pause_pair[1]))
    report["R2_input_extension"] = {
        "pair": pause_pair, "pause": "identity on full state; executed action 0",
        "release_outputs": tuple(read(update(z)) for z in pause_pair),
        "scope": "external pause/release input, not autonomous six-state model"}

    report["status"] = "PASS"
    return report


if __name__ == "__main__":
    print(json.dumps(verify(), ensure_ascii=False, indent=2))
